name: SimpleMerge
inputs:
  repo:
    required: true
    type: string
  pr_number:
    required: true
    type: number
  method:
    required: true
    type: string
    default: rebase
  force:
    required: false
    type: boolean
    default: false
  github_token:
    default: ${{ github.token }}
    required: false
  
runs:
  using: "composite"
  steps:
    - name: Merge
      shell: bash
      env:
        GH_TOKEN:       ${{inputs.github_token}}
      run: |
        ADMIN=""
        ${{inputs.force}} && ADMIN="--admin"
        gh pr merge --repo ${{inputs.repo}} --${{inputs.method}} $ADMIN ${{inputs.pr_number}}
