name: CherryPicker
inputs:
  asterisk_repo:
    required: true
    type: string
  pr_number:
    required: false
    type: number
    default: 0
  base_branch:
    required: true
    type: string
  push:
    required: false
    type: boolean
    default: false
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointCherryPicker.sh
