name: CreatePrivateFork
inputs:
  src_repo:
    description: 'Source asterisk org repo:'
    required: true
    type: string
  dst_repo:
    description: 'Destination asterisk org repo:'
    required: true
    type: string
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - name: CreateFork
      uses: asterisk/asterisk-ci-actions/CreatePrivateFork@main
      with:
        src_repo:          ${{inputs.src_repo}}
        dst_repo:          ${{inputs.dst_repo}}
        github_token:      ${{inputs.github_token}}
  
    - name: CopyVars
      uses: asterisk/asterisk-ci-actions/CopyRepoVariables@main
      with:
        src_repo:          ${{inputs.src_repo}}
        dst_repo:          ${{inputs.dst_repo}}
        github_token:      ${{inputs.github_token}}
