name: RunAsteriskGateTests
inputs:
  asterisk_repo:
    required: true
    type: string
  pr_number:
    required: true
    type: number
  pr_commit:
    required: true
    type: string
  base_branch:
    required: true
    type: string
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false
  cache_dir:
    default: cache
    required: false
  testsuite_repo:
    description: 'Testsuite Repo (default: asterisk/testsuite)'
    type: string
    required: true
  gatetest_group:
    description: 'Gate Group Number'
    type: number
    required: true
  gatetest_commands:
    description: 'Gate Commands'
    type: string
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointRunAsteriskGateTests.sh
