name: TestDockerAction
inputs:
  test_type:
    required: true
    type: string
outputs:
  result:
    description: 'result'

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointTestDocker.sh
