name: CherryPick
inputs:
  repo:
    required: true
    type: string
  pr_number:
    required: true
    type: number
  branch:
    required: true
    type: string
  cache_dir:
    default: cache
    required: false
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointCherryPick.sh
