name: CherryPick
inputs:
  repo:
    required: true
    type: string
  pr_number:
    required: true
    type: number
  branch:
    required: false
    type: string
  branches:
    required: false
    type: string
  push:
    required: false
    type: boolean
    default: false
  github_token:
    type: string
    required: true
  debug:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: CherryPick
      shell: bash
      env:
        BRANCH: ${{inputs.branch}}
        BRANCHES: ${{inputs.branches}}
        GITHUB_TOKEN: ${{inputs.github_token}}
        GH_TOKEN: ${{inputs.github_token}}
      run: |
        SCRIPT_DIR=$(dirname ${GITHUB_ACTION_PATH})/scripts
        export GH_TOKEN
        export GITHUB_TOKEN
        if [ -z "${BRANCH}" ] && [ -z "${BRANCHES}" ] ; then
          echo "::error::Either 'branch' or 'branches' must be supplied"
          exit 1
        fi
        if [ -n "${BRANCH}" ] && [ -n "${BRANCHES}" ] ; then
          echo "::error::You can't specify both 'branch' and 'branches' at the same time"
          exit 1
        fi
        if [ -n "${BRANCHES}" ] ; then
          words=$( echo "${BRANCHES}" | wc -w )
          if [ $words -ne 1 ] ; then
            echo "::error::'branches' can't contain whitespace"
            exit 1
          fi
        fi
        ${SCRIPT_DIR}/cherryPick.sh --repo=${{inputs.repo}} \
          ${BRANCH:+--branch=$BRANCH} \
          ${BRANCHES:+--branches="$BRANCHES"} \
          --pr-number=${{inputs.pr_number}} \
          --push=${{inputs.push}} || exit 1
