name: CreateAsteriskDocs
inputs:
  asterisk_repo:
    required: true
    type: string
  base_branch:
    required: true
    type: string
  docs_dir:
    required: false
    type: string
    default: docs_dir
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointCreateAsteriskDocs.sh
