name: CreateAsteriskDocsComposite
inputs:
  asterisk_repo:
    required: true
    type: string
  base_branch:
    required: true
    type: string
  docs_dir:
    required: false
    type: string
    default: docs_dir
  modules_blacklist:
    description: 'List of Asterisk modules to blacklist from the build'
    default: ""
    required: false
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - name: SetupUbuntuRunner
      uses: asterisk/asterisk-ci-actions/SetupUbuntuRunner@main

    - name: Get Asterisk
      uses: asterisk/asterisk-ci-actions/GetRepo@main
      with:
        repo:              ${{inputs.asterisk_repo}}
        base_branch:       ${{inputs.base_branch}}
        github_token:      ${{inputs.github_token}}
        build_script:      buildAsterisk.sh
        modules_blacklist: ${{inputs.modules_blacklist}}
  
    - name: Create Asterisk Docs for branch ${{inputs.base_branch}}
      uses: asterisk/asterisk-ci-actions/CreateAsteriskDocs@main
      with:
        asterisk_repo:       ${{inputs.asterisk_repo}}
        base_branch:         ${{inputs.base_branch}}
        docs_dir:            ${{inputs.docs_dir}}
        github_token:        ${{inputs.github_token}}

    - name: Reformat Branch
      id: reformat
      env:
        BRANCH: ${{inputs.base_branch}}
      shell: bash
      run: |
        echo "docname=documentation-${BRANCH//\//-}" >>${GITHUB_OUTPUT}

    - name: Save Output
      id: save-output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{steps.reformat.outputs.docname}}
        path: ${{inputs.docs_dir}}
