name: CopyRepoVariables
inputs:
  src_repo:
    description: 'Source asterisk org repo:'
    required: true
    type: string
  dst_repo:
    description: 'Destination asterisk org repo:'
    required: true
    type: string
  github_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: copyvars
      uses: actions/github-script@v7
      env:
        SRC_REPO: "${{inputs.src_repo}}"
        DST_REPO: "${{inputs.dst_repo}}"
      with:
        github-token: ${{ inputs.github_token }}
        retries: 5
        script: |
          let source = await github.paginate('GET /repos/{owner}/{repo}/actions/variables', {
            owner: 'asterisk',
            repo: `${process.env.SRC_REPO}`,
          })
          let existing = await github.paginate('GET /repos/{owner}/{repo}/actions/variables', {
            owner: 'asterisk',
            repo: `${process.env.DST_REPO}`,
          })
          let exists = {};
          for (const vv of existing) {
            exists[vv.name] = vv.value;
          }

          for (const vv of source) {
            if (typeof exists[vv.name] != "undefined") {
              uri = 'PATCH /repos/{owner}/{repo}/actions/variables/{name}';
              console.log(`Updating variable ${vv.name}`);
            } else {
              uri = 'POST /repos/{owner}/{repo}/actions/variables';
              console.log(`Creating variable ${vv.name}`);
            }
            await github.request(uri, {
              owner: 'asterisk',
              repo: `${process.env.DST_REPO}`,
              name: vv.name,
              value: vv.value
            })
          }
